export interface DefaultStandingItem {
  position: number;
  teamId: string;
  teamName: string;
  teamLogo: string | null;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  points: number;
  form: string;
  isUSM: boolean;
}

export const OFFICIAL_2026_2027_STANDINGS: DefaultStandingItem[] = [
  {
    position: 1,
    teamId: 'pss',
    teamName: 'PS Sakiet Eddaier',
    teamLogo: '/teams/pss.svg',
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 0,
    goalDifference: 3,
    points: 7,
    form: 'V-N-V',
    isUSM: false,
  },
  {
    position: 2,
    teamId: 'cab',
    teamName: 'CA Bizertin',
    teamLogo: '/teams/cab.png',
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 1,
    goalDifference: 2,
    points: 7,
    form: 'N-V-V',
    isUSM: false,
  },
  {
    position: 3,
    teamId: 'ca',
    teamName: 'Club Africain',
    teamLogo: '/teams/ca.png',
    played: 2,
    won: 2,
    drawn: 0,
    lost: 0,
    goalsFor: 2,
    goalsAgainst: 0,
    goalDifference: 2,
    points: 6,
    form: 'V-V',
    isUSM: false,
  },
  {
    position: 4,
    teamId: 'css',
    teamName: 'CS Sfaxien',
    teamLogo: '/teams/css.png',
    played: 2,
    won: 1,
    drawn: 1,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 2,
    goalDifference: 1,
    points: 4,
    form: 'V-N',
    isUSM: false,
  },
  {
    position: 5,
    teamId: 'usm',
    teamName: 'US Monastir',
    teamLogo: '/logo.png',
    played: 2,
    won: 1,
    drawn: 1,
    lost: 0,
    goalsFor: 2,
    goalsAgainst: 1,
    goalDifference: 1,
    points: 4,
    form: 'V-N',
    isUSM: true,
  },
  {
    position: 6,
    teamId: 'usbg',
    teamName: 'US Ben Guerdane',
    teamLogo: '/teams/usbg.png',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 2,
    goalsAgainst: 1,
    goalDifference: 1,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 7,
    teamId: 'ess',
    teamName: 'Étoile Sportive du Sahel',
    teamLogo: '/teams/ess.png',
    played: 2,
    won: 1,
    drawn: 0,
    lost: 1,
    goalsFor: 4,
    goalsAgainst: 4,
    goalDifference: 0,
    points: 3,
    form: 'V-D',
    isUSM: false,
  },
  {
    position: 8,
    teamId: 'esz',
    teamName: 'Espérance Sportive de Zarzis',
    teamLogo: '/teams/esz.png',
    played: 2,
    won: 1,
    drawn: 0,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 2,
    goalDifference: 0,
    points: 3,
    form: 'D-V',
    isUSM: false,
  },
  {
    position: 9,
    teamId: 'jso',
    teamName: 'JS Omrane',
    teamLogo: '/teams/jso.png',
    played: 2,
    won: 1,
    drawn: 0,
    lost: 1,
    goalsFor: 3,
    goalsAgainst: 3,
    goalDifference: 0,
    points: 3,
    form: 'V-D',
    isUSM: false,
  },
  {
    position: 10,
    teamId: 'est',
    teamName: 'Espérance Sportive de Tunis',
    teamLogo: '/teams/est.png',
    played: 2,
    won: 1,
    drawn: 0,
    lost: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 3,
    form: 'D-V',
    isUSM: false,
  },
  {
    position: 11,
    teamId: 'asm',
    teamName: 'Avenir Sportif de La Marsa',
    teamLogo: '/teams/asm.png',
    played: 2,
    won: 0,
    drawn: 1,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 1,
    goalDifference: -1,
    points: 1,
    form: 'N-D',
    isUSM: false,
  },
  {
    position: 12,
    teamId: 'eshs',
    teamName: 'ES Hammam Sousse',
    teamLogo: '/teams/eshs.png',
    played: 2,
    won: 0,
    drawn: 1,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 1,
    goalDifference: -1,
    points: 1,
    form: 'D-N',
    isUSM: false,
  },
  {
    position: 13,
    teamId: 'st',
    teamName: 'Stade Tunisien',
    teamLogo: '/teams/st.png',
    played: 2,
    won: 0,
    drawn: 1,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 3,
    goalDifference: -1,
    points: 1,
    form: 'D-N',
    isUSM: false,
  },
  {
    position: 14,
    teamId: 'ob',
    teamName: 'Olympique de Béja',
    teamLogo: '/teams/ob.png',
    played: 3,
    won: 0,
    drawn: 1,
    lost: 2,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 1,
    form: 'N-D-D',
    isUSM: false,
  },
  {
    position: 15,
    teamId: 'cshl',
    teamName: 'CS Hammam-Lif',
    teamLogo: '/teams/cshl.png',
    played: 2,
    won: 0,
    drawn: 0,
    lost: 2,
    goalsFor: 0,
    goalsAgainst: 2,
    goalDifference: -2,
    points: 0,
    form: 'D-D',
    isUSM: false,
  },
  {
    position: 16,
    teamId: 'esm',
    teamName: 'Étoile Sportive de Métlaoui',
    teamLogo: '/teams/esm.png',
    played: 2,
    won: 0,
    drawn: 0,
    lost: 2,
    goalsFor: 1,
    goalsAgainst: 3,
    goalDifference: -2,
    points: 0,
    form: 'D-D',
    isUSM: false,
  },
];
