export interface DefaultStandingItem {
  position: number;
  teamId: string;
  teamName: string;
  teamLogo: string | null;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  points: number;
  form: string;
  isUSM: boolean;
}

export const OFFICIAL_2026_2027_STANDINGS: DefaultStandingItem[] = [
  {
    position: 1,
    teamId: 'ps-sakiet-eddaier',
    teamName: 'PS Sakiet Eddaier',
    teamLogo: '/teams/pss.svg',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 2,
    goalsAgainst: 0,
    goalDifference: 2,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 2,
    teamId: '988',
    teamName: 'Espérance Sportive de Tunis',
    teamLogo: '/teams/est.png',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 2,
    goalDifference: 1,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 3,
    teamId: '987',
    teamName: 'Club Africain',
    teamLogo: '/teams/ca.png',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 1,
    goalsAgainst: 0,
    goalDifference: 1,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 4,
    teamId: '990',
    teamName: 'Club Athlétique Bizertin',
    teamLogo: '/teams/cab.png',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 1,
    goalsAgainst: 0,
    goalDifference: 1,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 5,
    teamId: '996',
    teamName: 'Espérance Sportive de Zarzis',
    teamLogo: '/teams/esz.png',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 1,
    goalsAgainst: 0,
    goalDifference: 1,
    points: 3,
    form: 'V',
    isUSM: false,
  },
  {
    position: 6,
    teamId: '989',
    teamName: 'Club Sportif Sfaxien',
    teamLogo: '/teams/css.png',
    played: 1,
    won: 0,
    drawn: 1,
    lost: 0,
    goalsFor: 1,
    goalsAgainst: 1,
    goalDifference: 0,
    points: 1,
    form: 'N',
    isUSM: false,
  },
  {
    position: 7,
    teamId: '993',
    teamName: 'Stade Tunisien',
    teamLogo: '/teams/st.png',
    played: 1,
    won: 0,
    drawn: 1,
    lost: 0,
    goalsFor: 1,
    goalsAgainst: 1,
    goalDifference: 0,
    points: 1,
    form: 'N',
    isUSM: false,
  },
  {
    position: 8,
    teamId: '992',
    teamName: 'US Monastir',
    teamLogo: '/logo.png',
    played: 1,
    won: 0,
    drawn: 1,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 1,
    form: 'N',
    isUSM: true,
  },
  {
    position: 9,
    teamId: '995',
    teamName: 'ES Hammam Sousse',
    teamLogo: '/teams/eshs.png',
    played: 1,
    won: 0,
    drawn: 1,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 1,
    form: 'N',
    isUSM: false,
  },
  {
    position: 10,
    teamId: '991',
    teamName: 'US Ben Guerdane',
    teamLogo: '/teams/usbg.png',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    form: '-',
    isUSM: false,
  },
  {
    position: 11,
    teamId: '994',
    teamName: 'CS Hammam-Lif',
    teamLogo: '/teams/cshl.png',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    form: '-',
    isUSM: false,
  },
  {
    position: 12,
    teamId: '986',
    teamName: 'Étoile Sportive du Sahel',
    teamLogo: '/teams/ess.png',
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 3,
    goalDifference: -1,
    points: 0,
    form: 'D',
    isUSM: false,
  },
  {
    position: 13,
    teamId: '997',
    teamName: 'Avenir Sportif de La Marsa',
    teamLogo: '/teams/asm.png',
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 1,
    goalDifference: -1,
    points: 0,
    form: 'D',
    isUSM: false,
  },
  {
    position: 14,
    teamId: '998',
    teamName: 'Étoile Sportive de Métlaoui',
    teamLogo: '/teams/esm.png',
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 1,
    goalDifference: -1,
    points: 0,
    form: 'D',
    isUSM: false,
  },
  {
    position: 15,
    teamId: '999',
    teamName: 'Olympique de Béja',
    teamLogo: '/teams/ob.png',
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 1,
    goalDifference: -1,
    points: 0,
    form: 'D',
    isUSM: false,
  },
  {
    position: 16,
    teamId: 'js-omrane',
    teamName: 'JS Omrane',
    teamLogo: '/teams/jso.png',
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 2,
    goalDifference: -2,
    points: 0,
    form: 'D',
    isUSM: false,
  },
];
